service: sls-az-func-rest-api
provider:
  name: azure
  region: West US 2
  runtime: nodejs10.x
  environment:
    VARIABLE_FOO: foo
plugins:
  - serverless-azure-functions
package:
  exclude:
    - local.settings.json
    - .vscode/**
functions:
  issues:
    handler: src/handlers/issues.handler
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
    name: sls-az-func-rest-api-dev-issues
  pulls:
    handler: src/handlers/pulls.handler
    events:
      - http: true
        x-azure-settings:
          authLevel: anonymous
    name: sls-az-func-rest-api-dev-pulls
  main:
    handler: src/handlers/main.handler
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous
    name: sls-az-func-rest-api-dev-main
  intro:
    handler: src/handlers/intro.handler
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous
    name: sls-az-func-rest-api-dev-intro
  profile:
    handler: src/handlers/profile.handler
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous
    name: sls-az-func-rest-api-dev-profile
  skills:
    handler: src/handlers/skills.handler
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous
    name: sls-az-func-rest-api-dev-skills
  contact-info:
    handler: src/handlers/contact-info.handler
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous
    name: sls-az-func-rest-api-dev-contact-info
  keep-warm:
    handler: src/handlers/keep-warm.handler
    events:
      - http: true
        x-azure-settings:
          methods:
            - GET
          authLevel: anonymous
    name: sls-az-func-rest-api-dev-keep-warm